/**
 * Treso Api specification
 * OpenApi documentation for Treso Api
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dev.cheikhIbrayade@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssetResponse } from './asset-response';


export interface ResponseAssetResponse { 
    statusCode?: number;
    errors?: Array<Error>;
    data?: Array<AssetResponse>;
}

